version: '3'

services:
    php:
        image: matthiasnoback/testing-playground-php:7.2
        build: docker/php/
        volumes:
            - ./:/opt/project:cached
        environment:
            XDEBUG_CONFIG: "remote_host=${DOCKER_HOST_NAME_OR_IP}"
        user: ${HOST_UID}:${HOST_GID}

    composer:
        image: composer:1.8
        volumes:
            - ./:/app:cached
            - ~/.composer:/tmp:cached
        user: ${HOST_UID}:${HOST_GID}
